### PR TITLE
Create better docs

### PR DESCRIPTION
**Pull request by UniqueName12345**

### CODE REVIEW

**Comment by GenericProgrammer1234** [comment]
Okay a few mistakes.

**Comment by GenericProgrammer1234** [comment]
It would be good if the docs was in a separate file and that file would be linked in the README.

**Comment by GenericProgrammer1234** [comment]
Also there is incorrect info here, looks like it's ChatGPT-made.

**Comment by GenericProgrammer1234** [comment]
> Displays a list of open windows, allowing you to switch between them.

You cannot switch between them right now.

**Comment by UniqueName12345** [comment]
> > Displays a list of open windows, allowing you to switch between them.
> You cannot switch between them right now.

I'll remove that line...

**Comment by GenericProgrammer1234** [comment]
There are more issues.

**Comment by GenericProgrammer1234** [comment]
> Use the arrow keys to navigate directories.

You cannot do that yet.

**Comment by GenericProgrammer1234** [comment]
Why is it repeating the `fs` command for different functions, it should just list it once.

**Comment by GenericProgrammer1234** [comment]
> Enter the visual editor mode by pressing the backtick key (\`) while in the editor.

Incorrect, you use the `v` command.

**Comment by UniqueName12345** [comment]
> > Use the arrow keys to navigate directories.
> 
> You cannot do that yet.

I'll remove that line as well. Problem is that I am maintaining two branches at once here.



> Why is it repeating the `fs` command for different functions, it should just list it once.

I'll do that too! Just don't expect me to do it quickly. Like I said, maintaining two branches!



> > Enter the visual editor mode by pressing the backtick key (`) while in the editor.
> 
> Incorrect, you use the `v` command.

I'll fix that.

**Comment by GenericProgrammer1234** [comment]
Okay, I didn't know you were maintaining two branches but Noml is pretty simple, writing docs yourself is way easier then writing docs with ChatGPT and needing to fix the mistakes.

**Comment by UniqueName12345** [comment]
> Okay, I didn't know you were maintaining two branches but Noml is pretty simple, writing docs yourself is way easier then writing docs with ChatGPT and needing to fix the mistakes.

I fixed all the mistakes anyway so :P

**Comment by GenericProgrammer1234** [comment]
Actually you ended up making a few more mistakes in fixing the mistakes. I am just going to write docs myself at this point.

**Comment by GenericProgrammer1234** [comment]
Also what is the purpose of the second branch?

**Comment by UniqueName12345** [comment]
> Also what is the purpose of the second branch?

There are two branches. One is "main" which is for everything and anything to do with Noml+ specifically (stuff like better efficency), while "forvanillanoml" is pretty much only for this specific Noml.

**Comment by UniqueName12345** [comment]
> Actually you ended up making a few more mistakes in fixing the mistakes.

Like what?



> I am just going to write docs myself at this point.

Go for it! I was just trying to help.

**Comment by GenericProgrammer1234** [comment]
> > Also what is the purpose of the second branch?

> There are two branches. One is "main" which is for everything and anything to do with Noml+ specifically (stuff like better efficency), while "forvanillanoml" is pretty much only for this specific Noml.

Wait, Noml+? Okay so this is getting out of the scope of this PR. We can discuss this in the forum.

**Comment by GenericProgrammer1234** [comment]
> > Actually you ended up making a few more mistakes in fixing the mistakes.

> Like what?

Well you use `v` to get into the visual editor but use \` to get out.



> > I am just going to write docs myself at this point.

> Go for it! I was just trying to help.

Well you could have at least put effort into helping if you were trying to help, I can also use ChatGPT to create the docs if I want. Thanks anyways.

**Comment by GenericProgrammer1234** [comment]
You are better with code so if you are going to make a PR again then make it be a code one.

**Pull request closed without merging**
